# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Minyeong
tagline:          'A Jekyll theme'
description:      'Currently software graphics engineer in <a href="http://jekyllrb.com" target="_blank">Dexter Studios</a>'
url:              https://minyeong-jeong.github.io/home
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           github.com/minyeong/home.git
